[editor]
command = "code"

[create]
auto_editor_open = true
auto_git_add = true
clipboard_message = "Create: ${url}"

[judge]
clipboard_message = "AC: ${url} ${lang}"

[language]
default = "pypy3"

[language.settings.cpp]
source_file_name = "main.cpp"
template_file = "templates/main.cpp"
[language.settings.cpp.commands]
version = "g++ --version"
compile = "g++ ${source_file} -o ${dir}/a.out"
execute = "${dir}/a.out"

[language.settings.pypy3]
source_file_name = "main.py"
template_file = "templates/main.py"
[language.settings.pypy3.commands]
version = "~/pypy3.6-v7.3.0-osx64/bin/pypy3 --version"
execute = "~/pypy3.6-v7.3.0-osx64/bin/pypy3 ${source_file}"

[language.settings.python3]
source_file_name = "main.py"
template_file = "templates/main.py"
[language.settings.python3.commands]
version = "python3 --version"
execute = "python3 ${source_file}"

[language.settings.ts]
source_file_name = "main.ts"
template_file = "templates/main.ts"
[language.settings.ts.commands]
version = "ts-node --version"
execute = "ts-node ${source_file}"
