[create]
post_create_commands = [
    "git add ${dir_path}/in ${dir_path}/out ${dir_path}/metadata.toml",
    "code . ${dir_path}/${source_file_name}",
]
clipboard_message = "Create: ${url}"

[judge]
clipboard_message = "AC: ${url} ${lang}"

[language]
default = "pypy3"

[language.settings.cpp]
source_file_name = "main.cpp"
template_file_path = "templates/main.cpp"
[language.settings.cpp.commands]
pre_execute = [
    "g++ --version",
    "g++ ${dir_path}/${source_file_name} -o ${dir_path}/a.out",
]
execute = "${dir_path}/a.out"
post_execute = ["rm ${dir_path}/a.out"]

[language.settings.pypy3]
source_file_name = "main.py"
template_file_path = "templates/main.py"
[language.settings.pypy3.commands]
pre_execute = ["~/pypy3.6-v7.3.0-osx64/bin/pypy3 --version"]
execute = "~/pypy3.6-v7.3.0-osx64/bin/pypy3 ${dir_path}/${source_file_name}"

[language.settings.python3]
source_file_name = "main.py"
template_file_path = "templates/main.py"
[language.settings.python3.commands]
pre_execute = ["python3 --version"]
execute = "python3 ${dir_path}/${source_file_name}"

[language.settings.ts]
source_file_name = "main.ts"
template_file_path = "templates/main.ts"
[language.settings.ts.commands]
pre_execute = [
    "pnpm tsc --version",
    "pnpm tsc --target ESNEXT --module commonjs ${dir_path}/${source_file_name}",
]
execute = "node ${dir_path}/main.js"
post_execute = ["rm ${dir_path}/main.js"]
