[package]
name = "kyopro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "=0.9.0"
proconio = { version = "=0.3.6", features = ["derive"] }
rspy = "0"
